server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost  #同一域名下共享cookie
spring:
  application:
    name: partner-backend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/partner?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234
  #redis配置、
  redis:
    host: localhost
    port: 6379
    database: 0
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)